version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: roundest_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devPassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
