// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Pokemon struct {
	ID   int32
	Name string
}

type Vote struct {
	ID             string
	CreatedAt      pgtype.Timestamp
	VotedForID     int32
	VotedAgainstID int32
}
