// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package queries

import (
	"context"
)

const checkIsSeeded = `-- name: CheckIsSeeded :one
SELECT EXISTS (
        SELECT 1
        FROM pokemon
    )
`

func (q *Queries) CheckIsSeeded(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, checkIsSeeded)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createPokemon = `-- name: CreatePokemon :exec
INSERT INTO pokemon (id, name)
VALUES ($1, $2)
`

type CreatePokemonParams struct {
	ID   int32
	Name string
}

func (q *Queries) CreatePokemon(ctx context.Context, arg CreatePokemonParams) error {
	_, err := q.db.Exec(ctx, createPokemon, arg.ID, arg.Name)
	return err
}

const getTwoRandomPokemon = `-- name: GetTwoRandomPokemon :many
SELECT id, name
FROM pokemon
ORDER BY RANDOM()
LIMIT 2
`

func (q *Queries) GetTwoRandomPokemon(ctx context.Context) ([]Pokemon, error) {
	rows, err := q.db.Query(ctx, getTwoRandomPokemon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pokemon
	for rows.Next() {
		var i Pokemon
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertVote = `-- name: InsertVote :exec
INSERT INTO vote (voted_for_id, voted_against_id)
VALUES ($1, $2)
`

type InsertVoteParams struct {
	VotedForID     int32
	VotedAgainstID int32
}

func (q *Queries) InsertVote(ctx context.Context, arg InsertVoteParams) error {
	_, err := q.db.Exec(ctx, insertVote, arg.VotedForID, arg.VotedAgainstID)
	return err
}
